source "https://rubygems.org"

# Core Rails
gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

# API & JSON
gem "jsonapi-serializer"
gem "rack-cors"
gem "jbuilder"

# Authentication & Authorization
gem "jwt"
gem "bcrypt", "~> 3.1.7"
gem "cancancan"

# Real-time & Background Jobs
gem "redis", "~> 5.0"
gem "sidekiq"

# Performance & Monitoring
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "rack-attack"
gem "bullet"

# Windows timezone data
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Development & Testing
group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-byebug"
  gem "rubocop-rails"
  gem "rubocop-rails-omakase", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
end

group :development do
  gem "listen"
  gem "spring"
  gem "annotate"
end
